version: '3'

services:
  # MySQL
  db:
    image: mysql:${VERSION}
    platform: linux/x86_64
    container_name: rdb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --general_log=1
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./fixtures:/opt/mysql:ro
    ports:
      - 3306:3306
