// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package book

import (
	"time"
)

type Book struct {
	ID          int32
	Title       string
	Version     int32
	PublishedAt time.Time
}
